pipeline{
    agent any
    tools{
        maven 'M2_HOME'   
    }
    stages{
         stage('Sonar-Scan'){
            steps{
                withSonarQubeEnv('SonarQube'){
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=NeneOps_dev-geo'
                }
                
            }
        }
        stage("maven-steps"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('Upload Artifacts'){
            steps{
                sh 'curl -uadmin:AP7iKibFPukTLYzjaqQWMbvj12T -T \
                target/bio*.jar \
                "http://18.232.174.150:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
    
}