pipeline{
    agent any
    tools{
        maven 'M2_HOME'   //the build tool
    }
    stages{
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
    }
    
}